import random
from datetime import date

from app.models import Category, Topic

_TECH: tuple[str, ...] = (
    "Digital twins in manufacturing",
    "Reinforcement learning for vehicle dispatching",
    "Automated material handling in semiconductor fabs",
    "Large language models as coding assistants",
    "Transformer attention explained for engineers",
    "Queueing theory and factory variability",
    "Predictive maintenance with sensor data",
    "Humanoid robots on the factory floor",
    "Vision-language-action models for robot manipulation",
    "Imitation learning from human demonstrations",
    "Simulation-to-real transfer in robotics",
    "Scheduling under uncertainty",
    "Supply chain resilience after disruptions",
    "Edge computing for real-time control",
    "Data quality and label noise in machine learning",
    "Federated learning and privacy",
    "Graph neural networks for logistics networks",
    "Diffusion models beyond image generation",
    "AI agents that use tools",
    "Evaluating LLMs: benchmarks and their limits",
    "Explainable AI for operations decisions",
    "Energy-aware computing in data centers",
    "Human-AI collaboration in engineering work",
    "The economics of automation and jobs",
    "Open-source versus proprietary AI models",
    "Anomaly detection in production lines",
    "Lean manufacturing meets machine learning",
    "Robot safety standards and certification",
    "Synthetic data for training perception models",
    "Optimization solvers versus learned heuristics",
    "Autonomous mobile robots versus fixed conveyors",
    "Why self-driving cars keep missing their deadlines",
    "Quantum computing: hype, hope, or both",
    "The right to repair your own devices",
    "Smart factories and the workers who run them",
    "Recommendation algorithms and what they do to taste",
    "Battery chemistry and the race past lithium",
    "Software bugs that cost lives",
    "Passwords, passkeys, and the end of remembering",
    "The limits of Moore's law",
)

_LITERATURE: tuple[str, ...] = (
    "Why Orwell's 1984 keeps returning to bestseller lists",
    "Kafka and the modern bureaucratic nightmare",
    "Han Kang and the international rise of Korean fiction",
    "The unreliable narrator from Nabokov to Ishiguro",
    "Dystopian fiction as social forecasting",
    "Science fiction that predicted real technology",
    "Why we still read Shakespeare",
    "The short story versus the novel",
    "Translation: what gets lost and what gets found",
    "Magical realism and Latin American history",
    "Poetry in the age of short attention spans",
    "Book bans and censorship battles today",
    "How literary prizes shape what the world reads",
    "Stoic philosophy's comeback in popular books",
    "Memoir and the ethics of writing about real people",
    "Murakami and the loneliness of the modern city",
    "Jane Austen's marriage plots in a dating-app age",
    "Detective fiction and why we like a solved crime",
    "Fantasy epics from Tolkien to game worlds",
    "The Great Gatsby and the myth of self-invention",
    "Dostoevsky's criminals and the question of guilt",
    "Camus and the absurd life",
    "Frankenstein: the first novel about technology",
    "Toni Morrison and the memory of slavery",
    "Chekhov and endings that refuse to end",
    "Fairy tales and what they teach children",
    "Poetry read at funerals and weddings",
    "Graphic novels as serious literature",
    "Audiobooks: reading or listening?",
    "Does reading fiction make you a better person?",
    "The great books canon and who decides",
    "Fan fiction and the ownership of characters",
    "The Little Prince and the adults who forgot",
    "Don Quixote and the hero who read too much",
    "Diaries and letters as literature",
    "The Nobel Prize in Literature and the politics of choosing",
    "The Odyssey and the long way home",
    "Crime writers and the cities they wrote about",
    "Rereading a book ten years later",
    "Literary translation in the age of machine translation",
)

_HISTORY: tuple[str, ...] = (
    "The Silk Road and the first global trade network",
    "How the printing press changed who could think in public",
    "The Black Death and the end of medieval Europe",
    "The Meiji Restoration: modernizing a nation in one generation",
    "The Industrial Revolution and the birth of the factory",
    "The Cold War space race",
    "The fall of the Berlin Wall and the end of a divided world",
    "The Mongol Empire and the largest land empire in history",
    "Colonialism's economic legacy in Asia and Africa",
    "The 1918 flu pandemic and lessons for today",
    "The Korean War in global context",
    "The Ottoman Empire's rise and fall",
    "Why the Roman Republic became an empire",
    "The Age of Exploration and the Columbian Exchange",
    "Women's suffrage movements around the world",
    "The invention of the nation-state",
    "The French Revolution and the invention of the citizen",
    "The Atlantic slave trade and the wealth it built",
    "The Great Depression and the birth of the welfare state",
    "Hiroshima and the decision to drop the bomb",
    "The Opium Wars and China's century of humiliation",
    "The partition of India and the lines drawn in haste",
    "The Vietnam War and the first televised conflict",
    "The Cuban Missile Crisis: thirteen days from war",
    "Ancient Athens and the first experiment in democracy",
    "The Crusades and the memory that outlived them",
    "The Renaissance and the rediscovery of the individual",
    "Marie Curie and the women science left out",
    "The Manhattan Project and the scientist's responsibility",
    "The Chernobyl disaster and the cost of secrecy",
    "The Apollo landing and what the money bought",
    "The Great Wall and the empires that built walls",
    "The Suez Crisis and the end of the British Empire",
    "The Japanese economic miracle and the lost decades",
    "The Reformation and the first information war",
    "The Scramble for Africa at a Berlin conference table",
    "The 2008 financial crisis and the bailouts that followed",
    "The Arab Spring and the revolutions that turned",
    "The Irish Famine and blame for a failed harvest",
    "Prohibition and the laws nobody obeyed",
)

# Standing arguments rather than this week's headline: the generator searches for
# the latest turn in each, so the pool does not go stale between sessions.
_WORLD: tuple[str, ...] = (
    "The global race to regulate AI",
    "Semiconductor export controls and technological sovereignty",
    "Critical minerals and the battery supply chain",
    "Falling birth rates and shrinking workforces",
    "Aging societies and the arithmetic of pensions",
    "Housing costs in the world's big cities",
    "Migration and border politics in Europe",
    "The electricity bill of the AI boom",
    "Who pays for the energy transition",
    "Insurance retreating from places extreme weather keeps hitting",
    "Water scarcity and the future of farming",
    "Undersea cables and the security of the internet",
    "Space debris and the crowding of low orbit",
    "Weight-loss drugs and the budgets of health systems",
    "Antibiotic resistance as a slow-moving emergency",
    "Deep-sea mining and the rules nobody agreed on",
    "Elections in an age of synthetic media",
    "Remote work, five years on",
    "Food export bans and global prices",
    "Carbon border taxes and the trade fights they start",
    "Four-day work weeks and the productivity question",
    "Universal basic income after the pilot programs",
    "The loneliness epidemic and who should fix it",
    "Screen time rules for children and for adults",
    "Tourism that ruins the places tourists love",
    "Fast fashion and the true cost of a cheap shirt",
    "Meat, plant-based meat, and the future of dinner",
    "Nuclear power's return as a climate answer",
    "The gig economy and the meaning of a job",
    "Sports gambling and the leagues that profit from it",
    "Private space companies and who owns orbit",
    "The global teacher shortage",
    "Cash, cards, and the end of physical money",
    "Cities built for cars and the fight to take them back",
    "The global talent race and brain drain",
    "Digital nomads and the towns they price out",
    "The World Cup and Olympics as national projects",
    "Ultra-processed food and the limits of personal choice",
    "Free speech and moderation on private platforms",
    "Wealth taxes and the billionaires who leave",
)

# Home ground for a pair of Korean learners: the arguments Koreans have among
# themselves, phrased so the article can look for the latest turn in each.
_KOREA: tuple[str, ...] = (
    "Korea's birth rate and what could reverse it",
    "Mandatory military service in a shrinking Korea",
    "Hagwon culture and the price of a university seat",
    "Seoul housing prices and the jeonse lease system",
    "Chaebol power and the reform that never comes",
    "Korea's dependence on semiconductor exports",
    "Regional decline beyond the Seoul metro area",
    "Nuclear power's place in Korea's energy mix",
    "Foreign workers in Korea's factories and farms",
    "Korea's pension arithmetic and the retirement age",
    "K-pop as soft power and as an industry",
    "The gender divide among young Koreans",
    "Korea's long working hours and the four-day week",
    "Delivery apps and gig work in Korean cities",
    "Medical school quotas and the doctors' strikes",
    "Korean unification: goal, slogan, or memory",
    "Korea's suicide rate and the mental health taboo",
    "Living alone in Korea and the convenience store economy",
    "Korean food's global moment, from kimchi to gimbap",
    "Twelve years of English class and still afraid to speak",
    "Naver and Kakao against the global platforms",
    "AI and the future of Korean manufacturing jobs",
    "Korea under Japanese rule and the memory that remains",
    "Seoul's subway and what other cities could copy",
    "Korean drama's global audience and the formula behind it",
    "The Korean coffee habit and the café economy",
    "Goshiwon, officetel, apartment: the Korean housing ladder",
    "Korean baseball and the fan culture of the KBO",
    "Esports as a national sport",
    "Jeju Island: paradise, overtourism, and water",
    "Korea's air quality and the fine dust from abroad",
    "The Korean age system and other things changed by law",
    "Plastic surgery and the pressure to look right",
    "Divided families and the reunions that stopped",
    "Multicultural Korea: marriage migrants and their children",
    "Korean startups in the shadow of the chaebol",
    "Digital government: Korea's public services online",
    "Korean webtoons and the comics industry",
    "Samsung, SK hynix, and the memory chip cycle",
    "The Sewol ferry and how a country grieves",
    "Elderly poverty in Korea and the cardboard collectors",
    "SKY universities and the ranking obsession",
)

# The working life of two master's students: how research gets done, judged,
# published and paid for.
_RESEARCH: tuple[str, ...] = (
    "How to read a paper in an hour",
    "The reproducibility crisis in machine learning research",
    "Peer review: broken, or the least bad option",
    "Master's, PhD, or industry: what the extra years buy",
    "Working with an advisor who is never around",
    "Publish or perish and the rise of paper mills",
    "LLMs as co-authors: where the line is",
    "Open access and who pays for publishing",
    "Conference deadlines and the culture of the all-nighter",
    "Negative results and why nobody publishes them",
    "Citation counts as a measure of a scientist",
    "Writing a thesis nobody will read",
    "Presenting research to people outside your field",
    "Simulation results versus the real factory floor",
    "Industry-funded research and its blind spots",
    "Lab culture: hierarchy, hours, and burnout",
    "Choosing a research topic that is still open in three years",
    "Benchmarks, leaderboards, and what they hide",
    "Research ethics beyond the consent form",
    "Writing papers in a second language",
    "The gap between a paper's claim and its code",
    "Academic conferences: networking, tourism, or science",
    "The literature review: reading everything, remembering nothing",
    "Coauthorship and who deserves to be on the paper",
    "Reviewer 2 and how to answer a hostile review",
    "Research in Korean labs versus American labs",
    "Impact factor and the journals that chase it",
    "Preprints: faster science or unchecked claims",
    "Grant writing as a genre of fiction",
    "Interdisciplinary research and the home nobody has",
    "Reproducing a result from someone else's code",
    "The 80-hour week and the myth of the heroic scientist",
    "Statistical significance and the p-value wars",
    "Mentoring undergraduates while still learning yourself",
    "Datasets: who collected them and who owns them",
    "The PhD job market outside academia",
    "Conference talks: slides, nerves, and the Q&A",
    "Retractions and the stories behind them",
    "Simulation studies and the parameters nobody reports",
    "A top journal or a fast one",
)


def _pool(texts: tuple[str, ...], category: Category) -> tuple[Topic, ...]:
    return tuple(Topic(text=t, category=category) for t in texts)


TECH_TOPICS = _pool(_TECH, Category.TECH)
LITERATURE_TOPICS = _pool(_LITERATURE, Category.LITERATURE)
HISTORY_TOPICS = _pool(_HISTORY, Category.HISTORY)
WORLD_TOPICS = _pool(_WORLD, Category.WORLD)
KOREA_TOPICS = _pool(_KOREA, Category.KOREA)
RESEARCH_TOPICS = _pool(_RESEARCH, Category.RESEARCH)

TOPICS: tuple[Topic, ...] = TECH_TOPICS + LITERATURE_TOPICS + HISTORY_TOPICS + WORLD_TOPICS + KOREA_TOPICS + RESEARCH_TOPICS


def pool_for_day(day: date, count: int, exclude: list[str] | None = None, salt: int = 0) -> list[Topic]:
    """The same slice all day, a different one tomorrow. Seeded by the date, plus a
    salt so a manual refresh can deal a fresh slice within the day."""
    taken = set(exclude or ())
    available = [t for t in TOPICS if t.text not in taken]
    rng = random.Random(day.toordinal() * 1000 + salt)
    rng.shuffle(available)
    return available[: max(0, count)]


def pick_topic(recent: list[str], rng: random.Random | None = None) -> str:
    rng = rng or random.Random()
    unused = [t.text for t in TOPICS if t.text not in set(recent)]
    return rng.choice(unused or [t.text for t in TOPICS])
